- name: Deploy Go app
  hosts: my_ec2_instance
  gather_facts: false
  become: true

  tasks:
    - name: Install Docker
      become: true
      dnf:
        name: docker
        state: present

    - name: Update DNF cache
      dnf:
        name: ""
        update_cache: yes
      register: dnf_update
      changed_when: false

    - name: Install python3-dnf
      dnf:
        name: python3-dnf
        state: present
      when: dnf_update is success

    - name: Start Docker service
      service:
        name: docker
        state: started
      become: true

    - name: Pull Docker image
      docker_image:
        name: aidanakhankeldieva/golang
        source: pull
        tag: latest

    - name: Run Docker container
      docker_container:
        name: go-app
        image: aidanakhankeldieva/golang
        state: started
        ports:
          - "8080:8080"
      register: docker_container_result

    - name: Print Docker container information
      debug:
        var: docker_container_result

    # - name: Check Go app health
    #   uri:
    #     url: http://ec2-18-214-159-174.compute-1.amazonaws.com:8080/health
    #     method: GET
    #     return_content: yes
    #   register: health_check_result

    # - name: Verify Go app health
    #   assert:
    #     that:
    #       - health_check_result.status == 200
    #     fail_msg: "Go app health check failed"
    #     success_msg: "Go app is running"
