- name: Deploy Go app
  hosts: my_ec2_instance
  gather_facts: false

  tasks:
    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Pull Docker image
      docker_image:
        name: aidanakhankeldieva/golang
        source: pull

    - name: Run Docker container
      docker_container:
        name: go-app
        image: aidanakhankeldieva/golang
        state: started
        restart_policy: always
