- name: Deploy Go app
  hosts: my_ec2_instance
  gather_facts: false

  tasks:
    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Update apt cache
      raw: sudo apt-get update
      register: apt_update
      changed_when: false

    - name: Install python3-apt
      apt:
        name: python3-apt
        state: present
      when: apt_update is success

    - name: Pull Docker image
      docker_image:
        name: aidanakhankeldieva/golang
        source: pull

    - name: Run Docker container
      docker_container:
        name: go-app
        image: aidanakhankeldieva/golang
        state: started
        restart_policy: always
