- name: Deploy Go app
  hosts: my_ec2_instance
  gather_facts: false

  tasks:
    - name: Install Docker
      become: true
      dnf:
        name: docker
        state: present

    - name: Update DNF cache
      dnf:
        name: ""
        update_cache: yes
      register: dnf_update
      changed_when: false

    - name: Install python3-dnf
      dnf:
        name: python3-dnf
        state: present
      when: dnf_update is success

    - name: Pull Docker image
      docker_image:
        name: aidanakhankeldieva/golang
        source: pull

    - name: Run Docker container
      docker_container:
        name: go-app
        image: aidanakhankeldieva/golang
        state: started
      register: docker_container_result

    - name: Print Docker container information
      debug:
        var: docker_container_result
