- name: Deploy Go app
  hosts: 18.214.159.174
  gather_facts: false

  tasks:
    - name: Pull Docker image
      docker_image:
        name: your-dockerhub-username/your-repo-name:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: go-app
        image: your-dockerhub-username/your-repo-name:latest
        state: started
        restart_policy: always
